### ISSUE TITLE
 In parseGrenades trajectory data, the grenade_type of "incgrenade" are incorrectly parsed as "molotov".

### ISSUE THREAD

**Issue by Yesber** [LaihoE/demoparser#111]
In parseGrenades trajectory data, the grenade_type of an incendiary are incorrectly parsed as a molotov.

**Comment by LaihoE** [comment]
fixed in 0.18.0

**Comment by Yesber** [comment]
the fix seems to track the trajectory of incendiaries dropped on the map, which is kind of cool but not what you would expect 😉
the thrown inc grenades still show up as molotovs

maybe this tech could be used to track where items have been dropped on the map, like for weapons, defuse kits and the bomb as well 👀

**Comment by LaihoE** [comment]
:laughing: maybe it is now fixed in 0.21.0. Sorry about the hassle

**Comment by Yesber** [comment]
seems to be fixed, thank you!
